name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push amd64
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          tags: |
            logzio/docker-metrics-collector:${{ github.event.release.tag_name }}
            logzio/docker-metrics-collector:latest

      - name: Build and push arm64
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.arm
          platforms: linux/arm64
          tags: |
            logzio/docker-metrics-collector:${{ github.event.release.tag_name }}
            logzio/docker-metrics-collector:latest
